wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: huggingface
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      2:
      - 1
      - 11
      4: 3.8.5
      5: 0.10.22
      8:
      - 1
      - 5
